# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_proto/user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user_proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15user_proto/user.proto\x12\nuser_proto\"\x07\n\x05\x45mpty\"s\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\x10\n\x08nickname\x18\x04 \x01(\t\x12\x15\n\rdate_of_birth\x18\x05 \x01(\t\x12\x11\n\tis_active\x18\x06 \x01(\x08\"+\n\x08UserList\x12\x1f\n\x05users\x18\x01 \x03(\x0b\x32\x10.user_proto.User2B\n\x0bUserService\x12\x33\n\x08GetUsers\x12\x11.user_proto.Empty\x1a\x14.user_proto.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=37
  _globals['_EMPTY']._serialized_end=44
  _globals['_USER']._serialized_start=46
  _globals['_USER']._serialized_end=161
  _globals['_USERLIST']._serialized_start=163
  _globals['_USERLIST']._serialized_end=206
  _globals['_USERSERVICE']._serialized_start=208
  _globals['_USERSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
